version: "3"

services:
  node:
    image: node:16
    container_name: store_manager
    tty: true
    stdin_open: true
    command: bash
    restart: always
    working_dir: /app
    volumes:
      - ./:/app
    depends_on:
      - db
    ports:
      - 3000:3000
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_HOST: db
      PORT: '3000'

  db:
    container_name: store_manager_db
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 3306:3306

networks:
  default:
    name: store_manager_net


# Atenção: Esse arquivo foi criado pelo time de instrução da Trybe e modificado por Nayara V.